import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Manrope } from "next/font/google";
import { Urbanist } from "next/font/google";
import "./globals.css";
import AptosWalletProvider from "./contexts/AptosWalletContext";

const inter = Inter({ subsets: ["latin"] });
const manrope = Manrope({ subsets: ["latin"] });
const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Paymaster-Example",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
    >
      <body>
        <AptosWalletProvider>
          <main>
            {children}
          </main>
        </AptosWalletProvider>
      </body>
    </html>
  );
}
